### PR TITLE
Upgrade to version 1.1 

### PR DESCRIPTION
**Pull request by ghost**
## Changes in this version:

- multiple bugs fixed
- support for PHP 8.1
- updated translations

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by ghost** [comment]
!testme

**Comment by ghost** [comment]
!bullseyetestme

**Comment by ghost** [comment]
!testme

**Comment by ghost** [comment]
**In my productive environment:**
Upgrade `1.0~ynh1` to `1.1~ynh1` on YunoHost 11.0.7 (testing) ✅

**Review by ericgaspar — COMMENTED** [review]
👍

The package could be improved by adding
- `DESCRIPTION.md`
- `screenshots` folder
- bringing last standards from `example_ynh`
- maybe we can set the password in `manifest.json` so we can remove the send email part...

**Comment by ghost** [comment]
- DESCRIPTION.md ✅
- screenshots folder ✅

The rest is beyond my knowledge` ¯\_(ツ)_/¯`

**Pull request merged**
